/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const after_Purchases_Read = require('./code/after-purchases-read');
const before_Purchases_Create_Update = require('./code/before-purchases-create-update');
const on_Redemptions_Redeem = require('./code/on-redemptions-redeem');

class fulldemoSrv extends LCAPApplicationService {
    async init() {

        this.after('READ', 'Purchases', async (results, request) => {
            await after_Purchases_Read(results, request);
        });

        this.before(['CREATE', 'UPDATE'], 'Purchases', async (request) => {
            await before_Purchases_Create_Update(request);
        });

        this.on('redeem', 'Redemptions', async (request) => {
            return on_Redemptions_Redeem(request);
        });

        return super.init();
    }
}


module.exports = {
    fulldemoSrv
};